eureka:
  client:
    ##开启健康检查
    healthcheck:
        enabled: true
    ##健康检查线程池大小
    heartbeat-executor-thread-pool-size: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
##超时配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  ##同一个Server重试的次数(除去首次)
  MaxAutoRetries: 2
  ##切换相同Server的次数
  MaxAutoRetriesNextServer: 0
  eureka:
    enabled: true

server:
  port: 8769
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000
spring:
  application:
    name: service-zuul
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    virtual-host: /localhost
#开启端点以及跨域,默认web只开启了health和info
management:
  endpoints:
    web:
      exposure: 
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        
zuul:
  max:
    host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
      max-per-route-connections: 1000
      max-total-connections: 1000
  ##是否开启重试功能  开启后对应的pom中需要加入spring-retry包
  retryable: true

  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
##绑定服务
    api-b:
      path: /api-b/**
      serviceId: service-config-refresh
    api-b-c:
      path: /api-b-c/**
      serviceId: service-config-refresh
##绑定具体ip
    api-a-url:
      path: /api-a-url/**
      url: http://bgapi.baimiwx.com
