##foo = foo version 2
##democonfigclient.message=hello spring io

## routes to serviceId
## routes to url
## zuul.routes.api-a-url.path=/userapi/**
## zuul.routes.api-a-url.url=http://localhost:8881/
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
foo: foo version 13

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-config-refresh
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    virtual-host: /localhost
#开启端点以及跨域,默认web只开启了health和info
management:
  endpoints:
    web:
      exposure: 
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
