##foo = foo version 2
##democonfigclient.message=hello spring io

## routes to serviceId
## routes to url
## zuul.routes.api-a-url.path=/userapi/**
## zuul.routes.api-a-url.url=http://localhost:8881/
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
foo: foo version 4
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-hi
  rabbitmq:
    host: 192.168.1.41
    username: admin
    password: admin
    port: 5672
    virtual-host: /
