spring:
  application:
    name: service-sms
  redis:
    database: 0
    host: 47.100.193.105
    port: 6379
    password: bmx84185858
    jedis:
      pool:
        max-active: 1024
        max-wait: -1ms
        max-idle: 300
        min-idle: 0
    timeout: 10000ms
  jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
    druid:
      url: jdbc:mysql://47.100.193.105:3306/xmbg?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: bmx
      password: 84185858
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
          db-type: mysql
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            none-base-statement-allow: false
            #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
            update-where-none-check: true
            #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
            select-into-outfile-allo: false
            #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
            metadata-allow: true
            #对被认为是攻击的SQL进行LOG.error输出
            wall.log-violation: true
            #对被认为是攻击的SQL抛出SQLExcepton
            wall.throw-exception: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        #置profileEnable能够监控单个url调用的sql列表
        profile-enable: true
        #session统计功能
        session-stat-enable: true
        #最大session数
        session-stat-max-count: 100
      stat-view-servlet:
        allow: 127.0.0.1
        login-username: admin
        login-password: bmx
        url-pattern: /druid/*
        reset-enable: true
        enabled: true
      aop-patterns: packages
#配置spring关联
#设置使用Cglib进行代理，因为部分需要代理的不是接口不适用于JDK动态代理，会报错
  aop:
    proxy-target-class: true


#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.100.193.105:3306/xmbg?useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: bmx
#    password: 84185858
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
#    poolPreparedStatements: true
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat, wall, log4j
#    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  client:
    ##开启健康检查
    healthcheck:
        enabled: true
    ##健康检查线程池大小
    heartbeat-executor-thread-pool-size: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
